### ISSUE TITLE
Question/Discussion: REPL history + copy-paste

### ISSUE THREAD

**Issue by mindreframer** [d4l3k/go-pry#28]
First: thanks for doing this, this it the most functional go repl out there! 

While not a big issue, but it would be nice to be able to copy-paste larger code blocks into the repl directly. History + tab completion would be the cherry on top of it. 

Here is a project that used the go impl. of readline with great success, maybe this could be something useful here? 

https://github.com/abiosoft/ishell

Cheers 
Roman

**Comment by d4l3k** [comment]
Yeah, definitely things on the roadmap!

History is actually implemented, but seems to have been broken. I'll look into that soon

**Comment by d4l3k** [comment]
@mindreframer history has been fixed.

**Comment by james-antill** [comment]
I just tried on 911b948de848ede38b1c229f8ecf4a8468968c1c and up arrow still does nothing.

**Comment by d4l3k** [comment]
Try running
```
go get -u github.com/mattn/go-tty
```

**Comment by james-antill** [comment]
Yeh, that fixed it and paste works too now. Is it possible to save/restore the history as you exit/restart?

**Comment by d4l3k** [comment]
Not currently but seems like an easy patch. Just dump the history array
into a file somewhere
